Comment: File ingest state machine
QueryLanguage: JSONata
StartAt: Prepare Lambda Payload

States:

  Prepare Lambda Payload:
    Type: Pass
    Assign:
      lambdaPayload:
        httpMethod: POST
        Headers:
          Content-Type:
            - application/json
        queryStringParameters: null
        body:
          type: SCHEDULE_INGESTION
          brand: ARQ
          detail: '{% $states.input.detail.bucket.name & $states.input.detail.object.key %}'
          org_id: '{% $states.input.id %}'
          channel: ARQTV3
    Next: Trigger work order create lambda

  Trigger work order create lambda:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Arguments:
      FunctionName: arn:aws:lambda:${region}:${aws_account_id}:function:${environment}-work_order_create
      Payload: '{% $lambdaPayload.body %}'
    Next: Extract Work Order Result

  Extract Work Order Result:
    Type: Pass
    Assign:
      workOrderStatusCode: '{% $states.input.Payload.statusCode %}'
      workOrderResponse: '{% $parse($states.input.Payload.body) %}'
    Next: Check Work Order Creation Status

  Check Work Order Creation Status:
    Type: Choice
    Choices:
      - Condition: '{% $workOrderStatusCode = 201 %}'
        Next: Prepare Hearst Schedule Mapper Payload
      - Condition: '{% $workOrderStatusCode = 200 %}'
        Next: Prepare Hearst Schedule Mapper Payload
      - Condition: '{% $workOrderStatusCode = 400 %}'
        Next: Work Order Creation Bad Request
      - Condition: '{% $workOrderStatusCode = 404 %}'
        Next: Work Order Creation Not Found
    Default: Work Order Creation Failed

  Prepare Hearst Schedule Mapper Payload:
    Type: Pass
    Assign:
      hearstMapperPayload:
        work_order_id: '{% $workOrderResponse.id %}'
        file_name: '{% $split($workOrderResponse.detail, "/")[count($split($workOrderResponse.detail, "/")) - 1] %}'
        vipe_channel_id: '{% $workOrderResponse.channel %}'
    Next: Trigger Hearst Schedule Mapper

  Trigger Hearst Schedule Mapper:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Arguments:
      FunctionName: arn:aws:lambda:${region}:${aws_account_id}:function:${environment}-hearst_schedule_mapper
      Payload: '{% $hearstMapperPayload %}'
    End: true

  Work Order Creation Bad Request:
    Type: Fail
    Error: WorkOrderCreationBadRequest
    Cause: Work order creation returned status code 400 (Bad Request)

  Work Order Creation Not Found:
    Type: Fail
    Error: WorkOrderCreationNotFound
    Cause: Work order creation returned status code 404 (Not Found)

  Work Order Creation Failed:
    Type: Fail
    Error: WorkOrderCreationFailed
    Cause: Work order creation did not return status code 200, 201, 400, or 404
